### ISSUE TITLE
Only picking black on Windows 10

### ISSUE THREAD

**Issue by mackyqueso** [kepi/chromeEyeDropper#103] opened 2017-06-06 23:59 UTC
When I go to choose a color from a web page it selects black (#000000) instead of the color.

**Comment by kepi** [comment] 2017-06-24 17:36
Thanks for report and sorry for trouble. Can you please specify which page you are trying color pick on? Also only to be sure. Did you restart chrome after eye dropper install (shouldn't be needed but ...)

**Comment by gabrielascj** [comment] 2017-07-20 14:58
the same is happening to me
the page is this one: http://www.cvonline.hu/allas?query=marketing+manager and I restarted chrome.

**Comment by kepi** [comment] 2017-09-08 17:08
Sorry for longer time to reply. I'm not able to reproduce this bug on any windows machine I tried :(

Can you please try it again with current Eye Dropper version? I don't suppose last version could fix anything but in combination with chrome updates, maybe...

If problem persist, can you please confirm version of Chrome you are experiencing this in? And also if you can work with developer tools console and can spare some time with me debugging, it can help me to pinpoint source of bug.

**Comment by saschmitz** [comment] 2017-09-23 19:32
Hey kepi,

Happening to me too - 

Google Chrome is up to date
Version 61.0.3163.100 (Official Build) (64-bit)

// ---------------------------------
    // COLORS
    // ---------------------------------

    pickColor: function(e) {
        if (page.canvasData === null)
            return;

        var canvasIndex = (e.pageX + e.pageY * page.canvas.width) * 4;
        ////console.log(e.pageX + ' ' + e.pageY + ' ' + page.canvas.width);

        var color = {
            r: page.canvasData[canvasIndex],
            g: page.canvasData[canvasIndex + 1],
            b: page.canvasData[canvasIndex + 2],
            alpha: page.canvasData[canvasIndex + 3]
        };

        color.rgbhex = page.rgbToHex(color.r, color.g, color.b);
        ////console.log(color.rgbhex);
        color.opposite = page.rgbToHex(255 - color.r, 255 - color.g, 255 - color.b);
        return color;
    },

    // i: color channel value, integer 0-255
    // returns two character string hex representation of a color channel (00-FF)
    toHex: function(i) {
        if (i === undefined) return 'FF'; // TODO this shouldn't happen; looks like offset/x/y might be off by one
        var str = i.toString(16);
        while (str.length < 2) {
            str = '0' + str;
        }
        return str;
    },

    // r,g,b: color channel value, integer 0-255
    // returns six character string hex representation of a color
    rgbToHex: function(r, g, b) {
        return page.toHex(r) + page.toHex(g) + page.toHex(b);
    },

    // ---------------------------------
    // UPDATING SCREEN
    // ---------------------------------

    checkCanvas: function() {
        // we have to create new canvas element
        if (page.canvas.width != (page.width + page.canvasBorders) || page.canvas.height != (page.height + page.canvasBorders)) {
            console.log('dropper: creating new canvas');
            page.canvas = document.createElement('canvas');
            page.canvas.width = page.width + page.canvasBorders;
            page.canvas.height = page.height + page.canvasBorders;
            page.canvasContext = page.canvas.getContext('2d');
            page.canvasContext.scale(1 / window.devicePixelRatio, 1 / window.devicePixelRatio);
            page.rects = [];
        }
    },

    screenChanged: function(force) {
        if (!page.dropperActivated)
            return;

        console.log("dropper: screenChanged");
        page.YOffset = $(document).scrollTop();
        page.XOffset = $(document).scrollLeft();

        var rect = {
            x: page.XOffset,
            y: page.YOffset,
            width: page.screenWidth,
            height: page.screenHeight
        };

        // don't screenshot if we already have this one
        if (!force && page.rects.length > 0) {
            for (index in page.rects) {
                if (page.rectInRect(rect, page.rects[index])) {
                    console.log('dropper: already shoted, skipping');
                    return;
                }
            }
        }

        page.screenshoting = true;

        $("#eye-dropper-overlay").css('cursor', 'progress')

        console.log('dropper: screenshoting');
        // TODO: this is terrible. It have to be done better way
        if (page.options.enableColorTooltip === true && page.options.enableColorToolbox === true) {
            page.elColorTooltip.hide(1, function() {
                page.elColorToolbox.hide(1, function() {
                    page.sendMessage({
                        type: 'screenshot'
                    }, function() {});
                });
            });
        } else if (page.options.enableColorTooltip === true) {
            page.elColorTooltip.hide(1, function() {
                page.sendMessage({
                    type: 'screenshot'
                }, function() {});
            });
        } else if (page.options.enableColorToolbox === true) {
            page.elColorToolbox.hide(1, function() {
                page.sendMessage({
                    type: 'screenshot'
                }, function() {});
            });
        } else {
            page.sendMessage({
                type: 'screenshot'
            }, function() {});
        }

    },

    // capture actual Screenshot
    capture: function() {
        page.checkCanvas();
        ////console.log(page.rects);

        //    var image = new Image();
        var image = document.createElement('img');

        image.onload = function() {
            page.screenWidth = image.width;
            page.screenHeight = image.height;

            var rect = {
                x: page.XOffset,
                y: page.YOffset,
                width: image.width,
                height: image.height
            };
            var merged = false;

            // if there are already any rectangles
            if (page.rects.length > 0) {
                // try to merge shot with others
                for (index in page.rects) {
                    var t = page.rectMerge(rect, page.rects[index]);

                    if (t != false) {
                        console.log('dropper: merging');
                        merged = true;
                        page.rects[index] = t;
                    }
                }
            }

            // put rectangle in array
            if (merged == false)
                page.rects.push(rect);

            page.canvasContext.drawImage(image, page.XOffset, page.YOffset);
            page.canvasData = page.canvasContext.getImageData(0, 0, page.canvas.width, page.canvas.height).data;
            // TODO - je nutne refreshnout ctverecek a nastavit mu spravnou barvu

            page.screenshoting = false;
            $("#eye-dropper-overlay").css('cursor', page.options.cursor);

            // re-enable tooltip and toolbox
            if (page.options.enableColorTooltip === true) {
                page.elColorTooltip.show(1);
            }
            if (page.options.enableColorToolbox === true) {
                page.elColorToolbox.show(1);
            }

            if ( DEBUG ) {
                page.sendMessage({type: 'debug-tab', image: page.canvas.toDataURL()}, function() {});
                debugger
            }
        }

        if (page.imageData) {
            image.src = page.imageData;
        } else {
            console.error('ed: no imageData');
        }
    },

    init: function() {
        page.messageListener();

        if ( page.width > CANVAS_MAX_SIZE ) {
            page.width = CANVAS_MAX_SIZE
        }
        if ( page.height > CANVAS_MAX_SIZE ) {
            page.height = CANVAS_MAX_SIZE
        }

    }
}

page.init();

window.onresize = function() {
    page.onWindowResize();
}



Hope this helps

**Comment by kepi** [comment] 2017-09-29 02:07
@saschmitz thanks for info. By "intermittently" you mean that on same page it sometime works and sometime don't? Or works on some pages only?

I'm trying to think about way to collect debug data from problem automatically, only way now would be probably through some remote session which isn't comfortable for either of us :) Info you sent is part of source code which won't help me unfortunately.

You can try this:

1. go to menu -> More tools -> Extensions
2. check checkbox Developer mode
3. find eye dropper between extensions
4. click on Inspect views: `background.html`
5. switch to `Console` tab

Leave that tab open and just try to pick colors as usual. When you see any error in background console tab, it may be usefull. Most important is to get info from time when you pick black instead of correct color.

Second thing you can try is reload background tab (simply pres ctrl+r in the background console window) and copy all info from console here, there may be some error at start.

**Closed** 2020-05-08 21:17 UTC
Labels: bug, medium

**Comment by kepi** [comment] 2020-05-08 21:22
I'm really sorry this took so long time, but issue should be finally fixed in version 0.5.4. New version is already published in Chrome Store and should be auto updated in your browser.
