### ISSUE TITLE
Add firefox support

### ISSUE THREAD

**Issue by Sundewplays** [kepi/chromeEyeDropper#247] opened 2024-01-24 07:11 UTC
### Describe the solution you'd like

I just want Firefox support so I can use this on Firefox and its forks, that would be cool and I'm sure lots of people would want this too.

**Comment by kepi** [comment] 2024-07-01 18:28
Also, I'm closing this in favor of same (but older) request and I'll update there. #175

**Comment by kepi** [comment] 2024-07-01 18:29
duplicate of #175

**Closed by kepi** 2024-07-01 18:28 UTC
Labels: type: idea

**Comment by Sundew-plays** [comment] 2024-07-01 21:47
Hey this is sundew yeah you can ping me if you want me to test id be glad to help you out

**Comment by Sundew-plays** [comment] 2024-07-01 21:48
I got new email so I am just migrating everything
