### ISSUE TITLE
Not picking up color from Images

### ISSUE THREAD

**Issue by JDracolyte** [kepi/chromeEyeDropper#142] opened 2020-03-31 16:41 UTC
Hello! I found that Eyedropper does not work on images, such as from Google or Instagram. I have seen other Eyedropper tools do this, can you fix it?

**Comment by kepi** [comment] 2020-03-31 17:15
Hello, you mean on downloaded images or directly on website with images? Can you send one URL where it doesn't work for you?

**Comment by JDracolyte** [comment] 2020-03-31 19:21
Sure: https://www.instagram.com/royale_designs/

**Comment by kepi** [comment] 2020-04-01 00:46
Hm, it is working without any problem for me. Can you describe where it differs from my experience (see attached screencast) or maybe attach screencast with your experience?

![ed_instagram](https://user-images.githubusercontent.com/105303/78087868-b96d0200-73c2-11ea-9e33-4c0a4ec657da.gif)

Thanks

**Comment by JDracolyte** [comment] 2020-04-01 02:57
It just shows up black or white when I hover over a pic. I'll uninstall it and see if it works

**Comment by kepi** [comment] 2020-04-01 03:25
Ah, in that case this is just duplicate of #141

I'll close this issue and continue in previous one. If by any chance you get it working, please let me know.

**Comment by kepi** [comment] 2020-04-01 03:25
Duplicate of #141

**Closed by kepi** 2020-04-01 03:25 UTC
Labels: Wait for details
