### ISSUE TITLE
Delete color from pallet 

### ISSUE THREAD

**Issue by JM141989** [kepi/chromeEyeDropper#143] opened 2020-04-21 19:41 UTC
So i get that i can make pallets and delete them.
but what if i want to only delete one or two colors....

is this even possible if not.... it should!

**Comment by kepi** [comment] 2020-04-21 21:44
Hey, thanks for feedback. Currently it isn't possible, but it totally make sense.

I'm working on new version currently, maybe I'll be able to squeeze it to next release. No promises.

**Comment by JM141989** [comment] 2020-04-21 23:05
Awesome thank you for the response!
Awesome little plugin man. :) 👍💯

**Comment by kepi** [comment] 2020-05-12 22:13
Just found out this is duplicate of #125 

Wasn't able to squeeze it to last release but I'll work on it soon I hope.

**Closed by kepi** 2020-05-12 22:13 UTC
Labels: medium, whishlist

**Comment by caleysueee** [comment] 2021-08-29 04:14
Any updates for being able to delete one or two colors from a palette?

**Comment by caleysueee** [comment] 2021-08-29 04:17
Nevermind. I was able to figure out how. :)
