### ISSUE TITLE
Suggestion for Eye Dropper on Crome Extension

### ISSUE THREAD

**Issue by saraak04** [kepi/chromeEyeDropper#242] opened 2023-10-03 04:48 UTC
### Is your feature request related to a problem?

I would like to select the eye dropped and it not drop.  Each time I select it, then click on a color, I have to reselect it (Alt P) and repeat.  I would like to keep the eye dropper active so all i have to do is click and click again.  Maybe a function that lets you activate the eye dropper and keep it on until you close the eye dropper function. 

### Describe the solution you'd like

Keep the eye dropper active till I turn it off.

### Describe alternatives you've considered

I would like to ALT P and keep the eye dropper active.  Each time I click on a color to pick, the eye dropper drops and I have to ALT P all over again.  Maybe add the ability to keep the eye dropper active. 

### Anything else?

no

**Comment by kepi** [comment] 2024-01-20 15:07
Thanks for your suggestion. I have this on TODO for long time, but didn't have time to implement it yet. I hope this might happen in near future, but no promisses.

I'll close this issue as it is duplicate of #26 but thanks for sending your feature request anyway.

**Closed by kepi** 2024-01-20 15:07 UTC
Labels: type: idea
