### ISSUE TITLE
Pick color from web page

### ISSUE THREAD

**Issue by GINGALLEY** [kepi/chromeEyeDropper#74] opened 2014-05-09 12:54 UTC
Picking color from web page no longer works for me. It used to but, now it doesn't? Any known issues? Using Version 0.3.6 with Chrome Version 34.0.1847.131. Thanks!

**Comment by kepi** [comment] 2015-01-19 15:49
Sorry for long delay, I really have no Mac OS to try this. Today I finally found someone with Mac to try but no problem appeared, picking is working without any issue.

Can I ask those with same problem to check with latest stable Chrome (should be 39)?

Is this issue present on multiple pages (i.e. try it here on github) or only on couple of them?

If problem is still present - have anybody of those with issue time to help me find root of problem? Some more interactive way to test (at least google chat, skype or similar) or in best case remote access to affected computer would be great.

Thanks

**Comment by GINGALLEY** [comment] 2015-01-19 16:05
Kepi,

Yes, I am still not able to get Eye Dropper to work. I was actually trying to use it yesterday and it wasn't picking color from a website.

Colorpicker: Version 0.3.6

Google Chrome: Version 39.0.2171.99 (64-bit)
Google Chrome is up to date.

I'd be willing to troubleshoot with you. Just let me know.

–Chris Gingrich

**Comment by kepi** [comment] 2015-01-20 09:45
Chris, do you have retina display? If so, can you see any other color than black on page if you move picker on the page?

**Comment by GINGALLEY** [comment] 2015-01-20 14:08
No retina display.

I only see black when I try to use.

–Chris

**Comment by kepi** [comment] 2015-02-07 15:24
@GINGALLEY in 60 minutes you should see updated version 0.3.7 in Chrome Extension Store. Could you please try it and tell me if something changed?

If not, please check if you aren't zoomed - in chrome menu check if font size is at 100 %.

If it still doesn't work please do following:

- open page www.google.com
- two fingers click and select inspect element
- change tab to console in just opened developer tools
- now active picking from web page and pick some color (no matter if it will show you black)
- copy me full output from console

Thanks

**Comment by GINGALLEY** [comment] 2015-02-07 15:29
Will do and let you know. Thanks!

–Chris

**Comment by GINGALLEY** [comment] 2015-02-10 17:18
Still doesn't work.

–Chris Gingrich

**Comment by kepi** [comment] 2015-02-11 13:14
@GINGALLEY can you send me output from dev console as I asked before? Thanks.

**Comment by GINGALLEY** [comment] 2015-03-04 12:47
I give up. Delete.

**Comment by kepi** [comment] 2015-03-04 14:14
Ok. Can anybody else give me data I need to fix this? i'll guide you to what I need. I has not been able to reproduce it on any computer :(

**Comment by BrianHannay** [comment] 2015-11-08 04:43
I'm having the same issue. Windows 10,  this is the console output from the extension popup. 
Another symptom is the color picker isn't loading but I think that is because the script died somewhere. 

Error in response to runtime.getBackgroundPage: TypeError: Cannot read property 'bg' of null
    at chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/popup.js:9:16
    at chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/popup.js:5:16handler @ extensions::uncaught_exception_handler:8
extensions::uncaught_exception_handler:8 Error in response to tabs.getSelected: TypeError: Cannot read property 'bg' of null
    at setDefaultColors (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/popup.js:53:29)
    at Object.callback (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/popup.js:37:9)
    at init (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/popup.js:19:17)
    at HTMLDocument.<anonymous> (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/popup.js:172:5)
    at j (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/inc/jquery-2.1.0.min.js:2:26676)
    at Object.k.fireWith [as resolveWith] (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/inc/jquery-2.1.0.min.js:2:27489)
    at Function.o.extend.ready (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/inc/jquery-2.1.0.min.js:2:29283)
    at HTMLDocument.I (chrome-extension://hmdcmlfkchdmnmnmheododdhjedfccka/inc/jquery-2.1.0.min.js:2:29453)

**Comment by kepi** [comment] 2016-07-11 15:28
@BrianHannay sorry for superlong reply :(

Will you be please so kind and test it again, if problem persist? I did some testing this weekend without any problem. Please be sure to restart browser after installing extension (it should work without but to be sure).

**Comment by GINGALLEY** [comment] 2016-07-11 15:34
Will do then.

Thanks!

–Chris Gingrich

(843)882-7224 | g@gingalley.com

**Comment by BrianHannay** [comment] 2016-07-11 18:43
Seems to be working for me

**Comment by GINGALLEY** [comment] 2016-07-11 18:49
Hey! It's working again for me. Thanks @kepi.

**Comment by kepi** [comment] 2016-07-12 12:02
Thanks for report! It didn't fix it, problem was almost certainly in specific builds in Chrome on both Mac and Windows around November 2015.

Thanks again, closing.

**Closed by kepi** 2016-07-12 12:02 UTC
Labels: critical, Wait for details
