### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by Ty-Thetravelguy** [kepi/chromeEyeDropper#250] opened 2024-02-20 08:40 UTC
### Describe the bug

I've tried it on multiple websites and nothing happenings. 

### Operating system

None

**Comment by kepi** [comment] 2024-02-20 08:46
@Ty-Thetravelguy thanks for report. Can you please fill more information? What operating system are you using? Did you try to restart browser after install?

Can you please describe exact steps you are doing (like I'm on site www..... , i click on eye dropper icon, selecting pick from wepage...), so I can check, what is wrong and fix it?

Thanks

**Comment by kepi** [comment] 2024-07-01 16:15
duplicate of #255

**Closed by kepi** 2024-07-01 16:15 UTC
Labels: res: waiting, type: bug
