### ISSUE TITLE
Option to go directly into color picking from toolbar icon

### ISSUE THREAD

**Issue by SirSteve** [kepi/chromeEyeDropper#147] opened 2020-06-11 17:25 UTC
As a user, I want to have the color picker activated as soon as I select the icon from the toolbar so that I can quickly "Pick my color from web page" rather than having to select the button for it.

**Comment by kepi** [comment] 2020-06-11 19:39
Thanks for opening the issue. This is "known issue" or better the one I'm thinking about for long time.

It would be great if you have any ideas how to implement this cleanly, meaning how to support single click web pickup but still be able to get to color history. I would be interested to know if maybe right click and context menu option to pickup color would do the trick? Let me known in #18 

I'm closing this as duplicate of #18  - lets keep the discussion there. I hope I can get to it after so many years :)

**Closed by kepi** 2020-06-11 19:39 UTC
